### ISSUE TITLE
New

### ISSUE THREAD

**Issue by andronwashere** [MicrosoftDocs/Contribute.ru-RU#4]
> hello world

>

**Comment by srvbpigh** [comment]
Hello, @andronwashere
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @andronwashere
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @andronwashere
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
